
services:

  clickhouse:
    image: clickhouse/clickhouse-server:23.3.8.21-alpine
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
    ports:
      - "8123:8123"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8123/ping || exit 1
      interval: 10s
      start_period: 10s
      timeout: 3s
      retries: 3

volumes:
  clickhouse-data:
    name: "ClickHouse_data"
