version: "3"

services:

  clickhouse:
    image: bitnami/clickhouse:latest
    volumes:
      - clickhouse-data:/bitnami/clickhouse
    environment:
      - CLICKHOUSE_ADMIN_USER=clickhouse
      - CLICKHOUSE_ADMIN_PASSWORD=clickhouse
    ports:
      - "8123:8123"

volumes:
  clickhouse-data:
    name: "ClickHouse_data"
