version: "3"

services:

  clickhouse:
    image: clickhouse/clickhouse-server:23.3.8.21-alpine
    volumes:
      - clickhouse-data:/bitnami/clickhouse
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
    ports:
      - "8123:8123"

volumes:
  clickhouse-data:
    name: "ClickHouse_data"
